FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt install -y libgl1-mesa-glx

COPY ai-engine/ .
COPY requirements_ai-engine.txt requirements.txt
COPY wait-for-db-init.sh /wait-for-db-init.sh

RUN chmod +x /wait-for-db-init.sh

RUN python3 -m venv /app/venv && \
    . /app/venv/bin/activate && \
    pip install --upgrade pip --quiet && \
    pip install --no-cache-dir -r requirements.txt --quiet 

ENV PYTHONPATH=/app
ENV LLM_MODEL="models/gemini-1.5-pro"
ENV EMBED_MODEL="models/embedding-001"

ENTRYPOINT ["/wait-for-db-init.sh"]

CMD ["/app/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]