FROM citusdata/citus:latest

# Copy the scripts
COPY wait-for-manager.sh /wait-for-manager.sh
COPY wait-for-db-init.sh /wait-for-db-init.sh
COPY update-pg-hba.sh /update-pg-hba.sh
COPY worker-entrypoint.sh /worker-entrypoint.sh

# Make them executable
RUN chmod +x /wait-for-manager.sh \
    && chmod +x /wait-for-db-init.sh \
    && chmod +x /update-pg-hba.sh \
    && chmod +x /worker-entrypoint.sh