FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY db-engine/change_listener.py \
     db-engine/main.py \
     db-engine/notifier.py \
     db-engine/requirements.txt \
     ./

ENV CACHE_ENGINE_ENDPOINT="http://cache_engine:6380"
ENV LLM_ENDPOINTS="http://ai_engine_1:8000,http://ai_engine_2:8000,http://ai_engine_3:8000"

RUN python3 -m venv /app/venv && \
    . /app/venv/bin/activate && \
    pip install --upgrade pip --quiet && \
    pip install --no-cache-dir -r requirements.txt --quiet 

CMD ["/app/venv/bin/python", "main.py"]