FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY db-engine/db-init.py /db-init.py
COPY db-engine/db-init.sh /db-init.sh
COPY db-engine/schema.sql /schema.sql

RUN  python3 -m venv /venv && \
    . /venv/bin/activate && \
    pip install --upgrade pip --quiet && \
    pip install --no-cache-dir --quiet psycopg2-binary==2.9.9

RUN chmod +x /db-init.sh
 
CMD ["bash", "/db-init.sh"]